### PR TITLE
assetConverter doc fix.

### PR DESCRIPTION
**Pull request by wiperawa**
$converter->setCommand expect 3 string parameters, there was 1 string and 1 array.
was to return statement in static function.

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by viktorprogger** [comment]
Thank you :+1:

**Comment by viktorprogger** [comment]
Could you please change other doc comments with this mistake?

**Comment by wiperawa** [comment]
Yes, will do today and change aliases also.

пт, 26 июн. 2020 г., 17:11 Viktor <notifications@github.com>:

**Comment by wiperawa** [comment]
> Could you please change other doc comments with this mistake?

changed one doc commend with same mistake in phpdoc comment

**Comment by samdark** [comment]
Thanks!

**Pull request merged**
